import { Component, computed, signal } from '@angular/core';
import { Sticker } from './sticker/sticker';
import { DonneeSticker } from './donnee-sticker.type';

@Component({
  selector: 'app-root',
  imports: [
    Sticker
  ],
  templateUrl: './app.html',
  styleUrl: './app.scss'
})
export class App {
  protected readonly title = signal('Panini / Top 14');

  protected readonly stickers = signal<DonneeSticker[]>([
  { id: 1, possession: true },
  { id: 2, possession: true },
  { id: 3, possession: false },
  { id: 4, possession: false },
  { id: 5, possession: true },
  { id: 6, possession: true },
  { id: 7, possession: true },
  { id: 8, possession: true },
  { id: 9, possession: false },
  { id: 10, possession: true },
  { id: 11, possession: false },
  { id: 12, possession: true },
  { id: 13, possession: true },
  { id: 14, possession: false },
  { id: 15, possession: false },
  { id: 16, possession: false },
  { id: 17, possession: false },
  { id: 18, possession: false },
  { id: 19, possession: false },
  { id: 20, possession: true },
  { id: 21, possession: false },
  { id: 22, possession: true, exemplaires: 2 },
  { id: 23, possession: true },
  { id: 24, possession: false },
  { id: 25, possession: false },
  { id: 26, possession: true },
  { id: 27, possession: false },
  { id: 28, possession: false },
  { id: 29, possession: false },
  { id: 30, possession: false },
  { id: 31, possession: true },
  { id: 32, possession: false },
  { id: 33, possession: false },
  { id: 34, possession: true },
  { id: 35, possession: false },
  { id: 36, possession: false },
  { id: 37, possession: false },
  { id: 38, possession: true },
  { id: 39, possession: true, exemplaires: 2 },
  { id: 40, possession: false },
  { id: 41, possession: false },
  { id: 42, possession: false },
  { id: 43, possession: true },
  { id: 44, possession: true },
  { id: 45, possession: true },
  { id: 46, possession: false },
  { id: 47, possession: false },
  { id: 48, possession: true },
  { id: 49, possession: false },
  { id: 50, possession: true },
  { id: 51, possession: true },
  { id: 52, possession: false },
  { id: 53, possession: false },
  { id: 54, possession: false },
  { id: 55, possession: false },
  { id: 56, possession: false },
  { id: 57, possession: true },
  { id: 58, possession: false },
  { id: 59, possession: false },
  { id: 60, possession: true },
  { id: 61, possession: true },
  { id: 62, possession: false },
  { id: 63, possession: true, exemplaires: 2 },
  { id: 64, possession: true },
  { id: 65, possession: false },
  { id: 66, possession: false },
  { id: 67, possession: false },
  { id: 68, possession: false },
  { id: 69, possession: false },
  { id: 70, possession: false },
  { id: 71, possession: false },
  { id: 72, possession: false },
  { id: 73, possession: false },
  { id: 74, possession: true },
  { id: 75, possession: true },
  { id: 76, possession: false },
  { id: 77, possession: true, exemplaires: 2 },
  { id: 78, possession: false },
  { id: 79, possession: false },
  { id: 80, possession: false },
  { id: 81, possession: false },
  { id: 82, possession: true, exemplaires: 2 },
  { id: 83, possession: false },
  { id: 84, possession: true },
  { id: 85, possession: true },
  { id: 86, possession: false },
  { id: 87, possession: true },
  { id: 88, possession: true },
  { id: 89, possession: false },
  { id: 90, possession: false },
  { id: 91, possession: true },
  { id: 92, possession: true, exemplaires: 2 },
  { id: 93, possession: true },
  { id: 94, possession: false },
  { id: 95, possession: false },
  { id: 96, possession: true },
  { id: 97, possession: true },
  { id: 98, possession: true },
  { id: 99, possession: true, exemplaires: 2 },
  { id: 100, possession: true },
  { id: 101, possession: true, exemplaires: 2 },
  { id: 102, possession: false },
  { id: 103, possession: false },
  { id: 104, possession: false },
  { id: 105, possession: false },
  { id: 106, possession: false },
  { id: 107, possession: true },
  { id: 108, possession: false },
  { id: 109, possession: true },
  { id: 110, possession: false },
  { id: 111, possession: false },
  { id: 112, possession: true },
  { id: 113, possession: false },
  { id: 114, possession: true, exemplaires: 2 },
  { id: 115, possession: true, exemplaires: 2 },
  { id: 116, possession: false },
  { id: 117, possession: true },
  { id: 118, possession: false },
  { id: 119, possession: true },
  { id: 120, possession: false },
  { id: 121, possession: true },
  { id: 122, possession: false },
  { id: 123, possession: false },
  { id: 124, possession: false },
  { id: 125, possession: false },
  { id: 126, possession: false },
  { id: 127, possession: false },
  { id: 128, possession: false },
  { id: 129, possession: true },
  { id: 130, possession: true },
  { id: 131, possession: false },
  { id: 132, possession: false },
  { id: 133, possession: false },
  { id: 134, possession: false },
  { id: 135, possession: false },
  { id: 136, possession: true },
  { id: 137, possession: true },
  { id: 138, possession: false },
  { id: 139, possession: false },
  { id: 140, possession: false },
  { id: 141, possession: false },
  { id: 142, possession: false },
  { id: 143, possession: true, exemplaires: 2 },
  { id: 144, possession: false },
  { id: 145, possession: true },
  { id: 146, possession: true, exemplaires: 2 },
  { id: 147, possession: false },
  { id: 148, possession: true },
  { id: 149, possession: true },
  { id: 150, possession: true, exemplaires: 2 },
  { id: 151, possession: false },
  { id: 152, possession: false },
  { id: 153, possession: false },
  { id: 154, possession: false },
  { id: 155, possession: false },
  { id: 156, possession: true },
  { id: 157, possession: false },
  { id: 158, possession: false },
  { id: 159, possession: false },
  { id: 160, possession: true, exemplaires: 2 },
  { id: 161, possession: false },
  { id: 162, possession: false },
  { id: 163, possession: false },
  { id: 164, possession: true },
  { id: 165, possession: true },
  { id: 166, possession: true },
  { id: 167, possession: false },
  { id: 168, possession: true, exemplaires: 2 },
  { id: 169, possession: false },
  { id: 170, possession: false },
  { id: 171, possession: true },
  { id: 172, possession: false },
  { id: 173, possession: false },
  { id: 174, possession: true, exemplaires: 2 },
  { id: 175, possession: false },
  { id: 176, possession: false },
  { id: 177, possession: false },
  { id: 178, possession: true },
  { id: 179, possession: false },
  { id: 180, possession: false },
  { id: 181, possession: true },
  { id: 182, possession: false },
  { id: 183, possession: false },
  { id: 184, possession: false },
  { id: 185, possession: false },
  { id: 186, possession: false },
  { id: 187, possession: true, exemplaires: 2 },
  { id: 188, possession: false },
  { id: 189, possession: false },
  { id: 190, possession: false },
  { id: 191, possession: false },
  { id: 192, possession: false },
  { id: 193, possession: true },
  { id: 194, possession: false },
  { id: 195, possession: false },
  { id: 196, possession: true },
  { id: 197, possession: false },
  { id: 198, possession: true },
  { id: 199, possession: false },
  { id: 200, possession: true },
  { id: 201, possession: true, exemplaires: 2 },
  { id: 202, possession: false },
  { id: 203, possession: false },
  { id: 204, possession: true, exemplaires: 2 },
  { id: 205, possession: false },
  { id: 206, possession: false },
  { id: 207, possession: true },
  { id: 208, possession: true },
  { id: 209, possession: true },
  { id: 210, possession: false },
  { id: 211, possession: false },
  { id: 212, possession: true },
  { id: 213, possession: true },
  { id: 214, possession: false },
  { id: 215, possession: true },
  { id: 216, possession: true },
  { id: 217, possession: false },
  { id: 218, possession: true, exemplaires: 2 },
  { id: 219, possession: false },
  { id: 220, possession: true },
  { id: 221, possession: true },
  { id: 222, possession: false },
  { id: 223, possession: true, exemplaires: 2 },
  { id: 224, possession: true },
  { id: 225, possession: false },
  { id: 226, possession: false },
  { id: 227, possession: true },
  { id: 228, possession: true },
  { id: 229, possession: false },
  { id: 230, possession: true },
  { id: 231, possession: false },
  { id: 232, possession: false },
  { id: 233, possession: true },
  { id: 234, possession: true },
  { id: 235, possession: false },
  { id: 236, possession: true },
  { id: 237, possession: false },
  { id: 238, possession: false },
  { id: 239, possession: true, exemplaires: 3 },
  { id: 240, possession: false },
  { id: 241, possession: true },
  { id: 242, possession: false },
  { id: 243, possession: true },
  { id: 244, possession: false },
  { id: 245, possession: true },
  { id: 246, possession: true },
  { id: 247, possession: true },
  { id: 248, possession: true },
  { id: 249, possession: false },
  { id: 250, possession: true },
  { id: 251, possession: false },
  { id: 252, possession: false },
  { id: 253, possession: false },
  { id: 254, possession: true },
  { id: 255, possession: true },
  { id: 256, possession: true },
  { id: 257, possession: false },
  { id: 258, possession: true },
  { id: 259, possession: true },
  { id: 260, possession: true },
  { id: 261, possession: false },
  { id: 262, possession: true },
  { id: 263, possession: false },
  { id: 264, possession: false },
  { id: 265, possession: false },
  { id: 266, possession: false },
  { id: 267, possession: false },
  { id: 268, possession: false },
  { id: 269, possession: false },
  { id: 270, possession: true },
  { id: 271, possession: false },
  { id: 272, possession: true },
  { id: 273, possession: true, exemplaires: 3 },
  { id: 274, possession: true },
  { id: 275, possession: false },
  { id: 276, possession: false },
  { id: 277, possession: false },
  { id: 278, possession: true },
  { id: 279, possession: false },
  { id: 280, possession: false },
  { id: 281, possession: false },
  { id: 282, possession: true },
  { id: 283, possession: true },
  { id: 284, possession: false },
  { id: 285, possession: false },
  { id: 286, possession: false },
  { id: 287, possession: true },
  { id: 288, possession: true },
  { id: 289, possession: false },
  { id: 290, possession: true },
  { id: 291, possession: true },
  { id: 292, possession: false },
  { id: 293, possession: false },
  { id: 294, possession: true },
  { id: 295, possession: false },
  { id: 296, possession: false },
  { id: 297, possession: true },
  { id: 298, possession: false },
  { id: 299, possession: true },
  { id: 300, possession: false },
  { id: 301, possession: false },
  { id: 302, possession: true },
  { id: 303, possession: false },
  { id: 304, possession: false },
  { id: 305, possession: false },
  { id: 306, possession: false },
  { id: 307, possession: false },
  { id: 308, possession: true },
  { id: 309, possession: true },
  { id: 310, possession: false },
  { id: 311, possession: true },
  { id: 312, possession: false },
  { id: 313, possession: false },
  { id: 314, possession: true, exemplaires: 2 },
  { id: 315, possession: true, exemplaires: 2 },
  { id: 316, possession: false },
  { id: 317, possession: false },
  { id: 318, possession: true, exemplaires: 2 },
  { id: 319, possession: false },
  { id: 320, possession: true, exemplaires: 2 },
  { id: 321, possession: false },
  { id: 322, possession: false },
  { id: 323, possession: false },
  { id: 324, possession: false },
  { id: 325, possession: true, exemplaires: 2 },
  { id: 326, possession: false },
  { id: 327, possession: false },
  { id: 328, possession: false },
  { id: 329, possession: true },
  { id: 330, possession: true },
  { id: 331, possession: true },
  { id: 332, possession: true },
  { id: 333, possession: true },
  { id: 334, possession: false },
  { id: 335, possession: false },
  { id: 336, possession: true, exemplaires: 2 }
]);

  protected readonly stickersPossedes = computed(() => this.stickers().filter(s => s.possession));
  protected readonly stickersManquants = computed(() => this.stickers().filter(s => !s.possession));
  protected readonly stickersEnDouble = computed(() => this.stickers().filter(s => (s.exemplaires || 0) > 1));

  protected stickerAffiches = signal(this.stickers());

  public afficherTousLesStickers(): void {
    this.stickerAffiches.set(this.stickers());
  }

  public afficherLesStickersPossedes(): void {
    this.stickerAffiches.set(this.stickersPossedes());
  }

  public afficherLesStickersManquants(): void {
    this.stickerAffiches.set(this.stickersManquants());
  }

  public afficherLesStickersEnDouble(): void {
    this.stickerAffiches.set(this.stickersEnDouble());
  }

}
